### ISSUE TITLE
Connection lost by timeout!

### ISSUE THREAD

**Issue by Nikita2k** [fyhertz/libstreaming#10]
Hi! I'm using your library to stream to wowza server.

I have problems connecting to wowza:
2013/11/19 21:13:57      background: Connecting to wowza server
2013/11/19 21:13:57      background: Connecting to 10.0.1.8:1935/live/test.stream
2013/11/19 21:13:57      background: quality set...
2013/11/19 21:13:57      background: credentials set. username: admin; password: admin
2013/11/19 21:13:57      background: server address set
2013/11/19 21:13:57      background: path set. Starting stream...
2013/11/19 21:15:28      background: starting stream failed: Connection lost
2013/11/19 21:15:28      background: starting stream failed: java.net.SocketException: Connection lost

Problem occurs on line:
mClient.startStream(1);

Wowza server is reacheable (I can ping it) and ip_address:1935 is visible from phone.

Do you have any workarounds?

**Comment by prashant31191** [comment]
Connection time out Error message shows any solution ??

java.net.ConnectException: failed to connect to /192.168.4.34 (port 1935): connect failed: ETIMEDOUT (Connection timed out)

net.majorkernelpanic.streaming.rtsp.RtspClient.tryConnection(RtspClient.java:309)
