### ISSUE TITLE
streaming.gl.SurfaceView: waiting time for new frame too long?

### ISSUE THREAD

**Issue by t-benze** [fyhertz/libstreaming#148]
In class streaming.gl.SurfaceView, the waiting time for synchronisation here is set to 2500 ms, ideally this should be fine as new frames keep coming in and notifying mSyncObject. However, in my testing, sometimes it will really wait for 2500ms and causes the preview to freeze. Changing the waiting time to a smaller value (e.g. 100) does fix the problem. But I'm not quite sure why this is happening, can anyone give some reasoning about this?

```
@Override
public void run() {
while (mRunning) {
  synchronized (mSyncObject) {
  mSyncObject.wait(2500);
  if (mFrameAvailable) {
  ....
  }
}
```

**Comment by Locnath** [comment]
Are you sure that there is no issue from camera? This thread should be woken up everytime there is a frame available from the camera driver. If you have the liberty of logging the android framework, I would recommend logging at camera HAL layer to ensure that the supply of camera frames is regular(should be ‘1000/fps’ milliseconds)
