### ISSUE TITLE
libstreaming should use Maven

### ISSUE THREAD

**Issue by soundmonster** [fyhertz/libstreaming#15]
To facilitate easy and automated inclusion in other projects, libstreaming should use [Maven](http://maven.apache.org/), at least as an option.

**Comment by nryabkov** [comment]
Guys, sorry for a stupid question - how can I link libstreaming as maven dependency for android studio build?

**Comment by androidneha** [comment]
Write this in your gradle file
` implementation 'com.github.fyhertz:libstreaming:3.0beta'`
