### ISSUE TITLE
Unable no video or audio from Wowza players

### ISSUE THREAD

**Issue by jd-alexander** [fyhertz/libstreaming#157]
I am using example 3 and trying to stream to Wowza. I see the connection in the incoming stream portal but no data is coming in. I know it's not a port/firewall issue becaue I used an iPhone RTSP app and I stream both audio and video to the server with no issues at all. So I'm wondering if anyone else got it working with Wowza and can give me some assistance.

**Comment by dirdiver** [comment]
I have it streaming (didn't use example 3). In our case it was a firewall issue on the server. 
We had to open the necessay ports

Dennis

**Comment by jd-alexander** [comment]
Ok thanks
