### ISSUE TITLE
prefix must not be bound to one of the reserved namespace names

### ISSUE THREAD

**Issue by winseyli** [fyhertz/libstreaming#171]
Hello, I am new to this libstreaming.
I am facing problem when importing example3 into Android Studio.
When compile and run, I get the error "Error:(2) Error parsing XML: prefix must not be bound to one of the reserved namespace names".
Can anyone give advice on solving this?
Sincerely appreciate and thank you so much!

**Comment by rush0621** [comment]
hi, coderwsli
i saw you closed this issue, i think u solved it, can you give some advice on how you did it?

**Comment by ahmadqureshii981** [comment]
rush do you solve this error ???

**Comment by ahmadqureshii981** [comment]
@rush0621  do you solve this error?

**Comment by ahmadqureshii981** [comment]
@coderwsli  do you solve this error?

**Comment by rush0621** [comment]
Nope

**Comment by WillieXie** [comment]
1. Open res/values/styles.xml
2. Remove attribute `xmlns:android="http://schemas.android.com/apk/res/android"` in two "style" nodes

3. Recompile Project.

**Comment by 328629033** [comment]
@WillieXie I tried this but not available.

**Comment by jilagan** [comment]
@WillieXie that fixed it for me. Thanks!
