### ISSUE TITLE
libstreaming not work in MODE_MEDIARECORDER_API mode with android 6.0

### ISSUE THREAD

**Issue by duohua** [fyhertz/libstreaming#208]
In Android 6.0，I set the libstreaming with MODE_MEDIARECORDER_API ,but it does not work.
It start failed. Could anyone give me some suggestions.I must use the MODE_MEDIARECORDER_API mode

**Comment by duohua** [comment]
Could someone help me？Thank you！

**Comment by sbaar** [comment]
It is no longer possible on 5.0+. You must use one of the other modes.

http://stackoverflow.com/questions/26990816/mediarecorder-issue-on-android-lollipop/27118142#27118142

**Comment by duohua** [comment]
@sbaar Thank you!
