### ISSUE TITLE
SurfaceVIew issue

### ISSUE THREAD

**Issue by umarmughal824** [fyhertz/libstreaming#214]
Its giving the error in that line 
mSession = SessionBuilder.getInstance()
                .setCallback(this)
                .setSurfaceView(mSurfaceView)
                .setPreviewOrientation(90)
                .setContext(getApplicationContext())
                .setAudioEncoder(SessionBuilder.AUDIO_NONE)
                .setAudioQuality(new AudioQuality(16000, 32000))
                .setVideoEncoder(SessionBuilder.VIDEO_H264)
                .setVideoQuality(new VideoQuality(320, 240, 20, 500000))
                .build();

the error is in that part ".setSurfaceView(mSurfaceView)" of it.
Its giving that error 
"in SessionBuilder cannot be applied to (net.majorkernelpanic.streaming.gl.SurfaceView)".

If I change it to android.view.SurfaceView it give that error
"in SessionBuilder cannot be applied to (android.view.SurfaceView)".

Where is that error coming from.

Please help to fix it.

Any suggestion will be appreciated.

thanks

**Comment by KPAXIT** [comment]
Probably your import in class is incorrect or the surfaceView in xml is wrong. Check example3 from libstreaming as an example eg.: 

Import: ` import net.majorkernelpanic.streaming.gl.SurfaceView;`

Xml: `<net.majorkernelpanic.streaming.gl.SurfaceView
            android:id="@+id/surface"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center" />`

Or your did not imported the libstreaming library well in the project (http://stackoverflow.com/questions/33539445/how-to-import-libstreaming-in-android-studio)
