### ISSUE TITLE
Callback buffer was too small on Samsung Galasy S2

### ISSUE THREAD

**Issue by devdao2002** [fyhertz/libstreaming#22]
Callback buffer was too small ! Expected 518400 bytes, but got 38016
![screen shot 2014-02-18 at 11 25 00 pm](https://f.cloud.github.com/assets/948955/2197174/4566b382-98b9-11e3-8e62-4987943afb78.png)

Quantity 640 x480 work but crash on resolution remain .

**Comment by promeG** [comment]
Hi, @gauravmishraitbhu 

I have the same issue. Could you please share which changes you have made to fix this? 

Thank you.
