### ISSUE TITLE
Adaptative encoding

### ISSUE THREAD

**Issue by asgarciap** [fyhertz/libstreaming#226]
Hi all,
Is it possibly to do adaptative encoding in real time using this library?
I'm developing (design part :) ) an application that would be streaming video from the phone to a rtp recorder server, so I want my app to detect if my network bandwith is bad and to decrease the quality of the video I'm sending to the server.
Any ideas? Thanks in advance.

**Comment by sbaar** [comment]
I made a few modifications to enable this. Some people didn't were confused last time I mentioned it, so just ask if you have any questions.
[https://gist.github.com/sbaar/c6dc432c7d175225f53b4c7c9119e02a](gist)

**Comment by mrluciusfox** [comment]
Thanks @sbaar , that's exactly what I'm looking for!
