### ISSUE TITLE
Marshmallow problems

### ISSUE THREAD

**Issue by DaviGia** [fyhertz/libstreaming#269]
Hi everyone,

I tried to use this library to stream camera and mic recording via rtsp but so far I haven't found a single config working.
I tried nearly all fixes I found on the net and none of them worked. I have a 
Huawei Honor 5X with Android 6.0.1 and I'm trying to record at SD/720p/1080p at 30fps/24fps at 3/1 Mbps with MODE_MEDIACODEC_API_2 set as default streaming mode.

The problem is that when .debug() method is triggered the dummy frame is encoded but never decoded, every decoder found just return -1 (INFO_TRY_AGAIN_LATER) when dequeueOutputBuffer is called (I have increased all timeouts up to 1 minute), so it basically times out each time. 

If I skip the .debug() method completely the encode starts, or at least I guess so, because I see that onBitrateUpdate is triggered (even if the value is very very small, like 100 Kbps max). But the preview seems very laggy, I cannot access the rtsp stream via VLC or ffplay and on the logcat I see that error: V/MediaCodecInputStream﹕ No buffer available...

So the main problem is that the MediaCodec seems to not decode anything. Maybe is it due to a synchronous implementation of MediaCodec? Have someone tried to use asynchronous callback from the object to read buffers? Is it working? What about update code to use camera2 api?

On the other hand with MODE_MEDIARECORDER_API I get another error:
E/MediaRecorder: start failed: -2147483648
W/System.err: java.lang.RuntimeException: start failed. W/System.err: at android.media.MediaRecorder.start(Native Method)

As far as I understand that error is throwed because the ParcelFileDescriptor is not seekable and since API 23 that it's no more allowed.
Is there a new workaround for this error?

Thanks in advance.

**Comment by pedroSG94** [comment]
You can try with other library:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java

**Comment by DaviGia** [comment]
>  pedroSG94 
Wow, that is exactly what I needed. Can you provide an example on how to use your library to stream audio and video via RTSP without a surfaceView (I need to use it on a Service and I don't need to show the playback to the user). I'm interested in the Camera2Base builder.
