### ISSUE TITLE
RTSP server using 3G AND vlc

### ISSUE THREAD

**Issue by ssppgit** [fyhertz/libstreaming#30]
Hi!

I am using this library for doing streaming for my android phone to VLC.

In a local network, I get to watch the streaming in VLC OK, but when i disable wifi and i Use 3g/lte, I don't get to watch the streaming in VLC. 

I am using example 1 of libstreaming-examples

Is it possible? And how? Thanks!

**Comment by tulkas85** [comment]
I not think that port forwarding is enough, the only way I found for that is to use Wowza in the middle.
