### ISSUE TITLE
B


### ISSUE THREAD

**Issue by Alexsabik** [fyhertz/libstreaming#309]
J
<div class="container"> <div class="row"> <div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2"> <form [formGroup]="signupForm" (ngSubmit)="onSubmit()"> <div formGroupName="userData"> <div class="form-group"> <label for="username">Username</label> <input type="text" id="username" formControlName="username" class="form-control"> <span *ngIf="!signupForm.get('userData.username').valid && signupForm.get('userData.username').touched" class="help-block"> <span *ngIf="signupForm.get('userData.username').errors['nameIsForbidden']">This name is invalid!</span> <span *ngIf="signupForm.get('userData.username').errors['required']">This field is required!</span> </span> </div> <div class="form-group"> <label for="email">email</label> <input type="text" id="email" formControlName="email" class="form-control"> <span *ngIf="!signupForm.get('userData.email').valid && signupForm.get('userData.email').touched" class="help-block">Please enter a valid email!</span> </div> </div> <div class="radio" *ngFor="let gender of genders"> <label> <input type="radio" formControlName="gender" [value]="gender">{{ gender }} </label> </div> <div formArrayName="hobbies"> <h4>Your Hobbies</h4> <button class="btn btn-default" type="button" (click)="onAddHobby()">Add Hobby</button> <div class="form-group" *ngFor="let hobbyControl of signupForm.get('hobbies').controls; let i = index"> <input type="text" class="form-control" [formControlName]="i"> </div> </div> <span *ngIf="!signupForm.valid && signupForm.touched" class="help-block">Please enter valid data!</span> <button class="btn btn-primary" type="submit">Submit</button> </form> </div> </div> </div>

**Comment by Alexsabik** [comment]
<div class="container"> <div class="row"> <div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2"> <form [formGroup]="signupForm" (ngSubmit)="onSubmit()"> <div formGroupName="userData"> <div class="form-group"> <label for="username">Username</label> <input type="text" id="username" formControlName="username" class="form-control"> <span *ngIf="!signupForm.get('userData.username').valid && signupForm.get('userData.username').touched" class="help-block"> <span *ngIf="signupForm.get('userData.username').errors['nameIsForbidden']">This name is invalid!</span> <span *ngIf="signupForm.get('userData.username').errors['required']">This field is required!</span> </span> </div> <div class="form-group"> <label for="email">email</label> <input type="text" id="email" formControlName="email" class="form-control"> <span *ngIf="!signupForm.get('userData.email').valid && signupForm.get('userData.email').touched" class="help-block">Please enter a valid email!</span> </div> </div> <div class="radio" *ngFor="let gender of genders"> <label> <input type="radio" formControlName="gender" [value]="gender">{{ gender }} </label> </div> <div formArrayName="hobbies"> <h4>Your Hobbies</h4> <button class="btn btn-default" type="button" (click)="onAddHobby()">Add Hobby</button> <div class="form-group" *ngFor="let hobbyControl of signupForm.get('hobbies').controls; let i = index"> <input type="text" class="form-control" [formControlName]="i"> </div> </div> <span *ngIf="!signupForm.valid && signupForm.touched" class="help-block">Please enter valid data!</span> <button class="btn btn-primary" type="submit">Submit</button> </form> </div> </div> </div>

**Comment by hthetiot** [comment]
@Alexsabik I can see you are a new GitHub user and you "learning" you should not create useless issue like that on other project repository, this notified hundred of people for nothing and make maitainer of those projects lose precious time that they can use to instead maintain there projet and fixes issues. Please close this issue by yourself, so you don't waste the maintainer time.
