### ISSUE TITLE
Can you stream with RTMP?

### ISSUE THREAD

**Issue by lfdversluis** [fyhertz/libstreaming#95]
Can you stream with the RTMP on Android using this library? If no, does anyone know which library does support this? I am searching everywhere for a decent library.

**Comment by gauravmishraitbhu** [comment]
as far as i know this lib does not support RTMP. 
to answer which library does , you can take a look at  http://www.realtimelibs.com/ .
this is a paid library though.

**Comment by lfdversluis** [comment]
Thanks :)
