### ISSUE TITLE
Streaming video is rotated

### ISSUE THREAD

**Issue by serpro** [fyhertz/libstreaming#96]
I tried the example3 from your code, and the camera is rotated 90 CCW, but on Wowza the video is rotated 90 CW!. I used the code from here: http://stackoverflow.com/questions/3841122/android-camera-preview-is-sideways to fix the rotation in the preview, but the video on the server is still rotated (Tested with Nexus 7 Running Android Lollipop and OnePlus One Running 4.4.4).

Any suggestions?

**Comment by tneginareb** [comment]
Explore "libstreaming" library then go to:


 1. VideoStream.java class 
 2. Find createCamera() method, replace "mCamera.setDisplayOrientation(mOrientation);"
with mCamera.setDisplayOrientation(90);
 3. Find updateCamera(),  replace "mCamera.setDisplayOrientation(mOrientation);"
with "mCamera.setDisplayOrientation(90);"
 4. Find updateCamera(),  replace "mCamera.setDisplayOrientation(mOrientation);"
with "mCamera.setDisplayOrientation(90);
